apiVersion: v1
kind: Template
parameters:
- name: IMAGE_TAG
  value: latest
  required: true
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    generation: 1
    name: osd-managed-prometheus-exporter-ebs-iops-reporter
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
        hive.openshift.io/cluster-platform: "aws"
    resourceApplyMode: Sync
